// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"poker/internal/api/controller"
	"poker/internal/api/model"
	"poker/internal/api/repository"
	"poker/internal/api/route"
	"poker/internal/api/service"
)

// Injectors from wire.go:

func InitializeApp() (*route.Route, error) {
	db := model.InitMysql()
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userController := controller.NewUserController(userService)
	userRoute := route.NewUserRoute(userController)
	routeRoute := route.NewRoute(userRoute)
	return routeRoute, nil
}
